version: '3.8'

services:
  invoice-service:
    build:
      context: ./invoice-creation-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=your amp url
      - SALES_REPORT_QUEUE=sales_summary_queue
      - MONGODB_URI= your mongodb uri

  consumer-service:
    build:
      context: ./consumer-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqps://msactcbs:T_PHvEtd5u941rLQJIHnokEHJL_dBVh6@puffin.rmq2.cloudamqp.com/msactcbs
      - SALES_REPORT_QUEUE=sales_summary_queue
   
   

